<a href="https://colab.research.google.com/github/kickmyd2602/AIML/blob/main/mlpractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NAIVE BAYES WITH PACKAGE

In [28]:
import numpy as np #math
import pandas as pd #dataset
from sklearn.model_selection import train_test_split as tts #train test
from sklearn.naive_bayes import GaussianNB #model selection
from sklearn.metrics import accuracy_score, confusion_matrix

In [29]:
data = pd.read_csv('/1683093619109_Iris.csv', index_col = 'Id')
data.head()


SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id                                                                       
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa

In [30]:
data.describe()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count     150.000000    150.000000     150.000000    150.000000
mean        5.843333      3.054000       3.758667      1.198667
std         0.828066      0.433594       1.764420      0.763161
min         4.300000      2.000000       1.000000      0.100000
25%         5.100000      2.800000       1.600000      0.300000
50%         5.800000      3.000000       4.350000      1.300000
75%         6.400000      3.300000       5.100000      1.800000
max         7.900000      4.400000       6.900000      2.500000

In [31]:
features = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']
x = data[features]
y = data['Species']

In [32]:
x_train, x_test, y_train , y_test = tts(x, y, test_size = 0.25, random_state = 1)
model = GaussianNB()
model.fit(x_train, y_train)

GaussianNB()

In [33]:
y_predict = model.predict(x_test)

In [34]:
print(accuracy_score(y_test, y_predict)*100)

97.36842105263158


In [35]:
print(confusion_matrix(y_test, y_predict))

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


# NAIVE BAYES W/O PACKAGE


In [52]:
import numpy as np
import pandas as pd

def calculate_prob(x, mean, variance):
    exponent = np.exp(-(x - mean)**2 / (2 * variance))
    return exponent / np.sqrt(2 * np.pi * variance)

data = pd.read_csv('/1683093619109_Iris.csv', index_col=0)
data['Species'].replace('Iris-setosa',1,inplace=True)
data['Species'].replace('Iris-versicolor',2,inplace=True)
data['Species'].replace('Iris-virginica',3,inplace=True)

class_label = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
features = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']

AM = np.zeros((len(features), len(class_label)))
AV = np.zeros((len(features), len(class_label)))

for i, label in enumerate(class_label, start=1):
    clas = data[data['Species'] == i]
    for j, feature in enumerate(features):
        AM[j, i-1] = np.mean(clas[feature])
        AV[j, i-1] = np.var(clas[feature])

print("Enter inputs:")
x = [float(input(f"Enter the {feature}: ")) for feature in features]

A = np.array([calculate_prob(x[i], AM[i], AV[i]) for i in range(len(features))])

print(A)

predicted_class = class_label[np.argmax(np.prod(A, axis=0))]
print(predicted_class)



Enter inputs:
Enter the SepalLengthCm: 3.2
Enter the SepalWidthCm: 3.5
Enter the PetalLengthCm: 3.9
Enter the PetalWidthCm: 3.3
[[1.74392504e-006 4.64538140e-007 3.24870561e-007]
 [1.03295597e+000 8.11892610e-002 3.21601907e-001]
 [4.91434167e-044 6.35673229e-001 7.55259624e-003]
 [3.43024526e-180 1.69924868e-022 2.50513184e-005]]
Iris-virginica


# KNN WITH PACKAGE

In [39]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split as ttp
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [53]:
data = pd.read_csv('/1683093619109_Iris.csv', index_col = 'Id')
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id                                                                       
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa

In [41]:
data.describe()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count     150.000000    150.000000     150.000000    150.000000
mean        5.843333      3.054000       3.758667      1.198667
std         0.828066      0.433594       1.764420      0.763161
min         4.300000      2.000000       1.000000      0.100000
25%         5.100000      2.800000       1.600000      0.300000
50%         5.800000      3.000000       4.350000      1.300000
75%         6.400000      3.300000       5.100000      1.800000
max         7.900000      4.400000       6.900000      2.500000

In [42]:
features = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']
x = data[features]
y = data['Species']

In [46]:
x_train, x_test, y_train, y_test = tts(x, y, test_size = 0.25, random_state = 1)
k=5
model = KNeighborsClassifier(n_neighbors = k)
model.fit(x_train, y_train)

KNeighborsClassifier()

In [47]:
y_predict = model.predict(x_test)
print(accuracy_score(y_test, y_predict)*100)

100.0


In [45]:
print(confusion_matrix(y_test, y_predict))

[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]


# KNN W/O PACKAGE

In [50]:
import pandas as pd
import numpy as np

data = pd.read_csv("/1683093619109_Iris.csv", index_col=0)
data['Species'].replace('Iris-setosa',1,inplace = True)
data['Species'].replace('Iris-versicolor',2,inplace = True)
data['Species'].replace('Iris-virginica',3,inplace = True)
class_label = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
features = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']

print("Enter the input:")
sample = [float(input(f"Enter the {feature}: ")) for feature in features]
k = 75
data['Distance'] = np.sum((data[features] - sample) ** 2, axis=1)
sorted_data = data.sort_values(by='Distance')
output = sorted_data.iloc[:k, 4]
predicted_label = class_label[output.values[0] - 1]

print(predicted_label)



Enter the input:
Enter the SepalLengthCm: 3.2
Enter the SepalWidthCm: 3.5
Enter the PetalLengthCm: 3.9
Enter the PetalWidthCm: 3.3
Iris-virginica


# LINEAR REGRESSION WITH PACKAGE

In [54]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split as tts
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [72]:
data = pd.read_csv('/1683093614543_weight-height.csv', index_col = 0)
data.head()

Height      Weight
Gender                       
Male    73.847017  241.893563
Male    68.781904  162.310473
Male    74.110105  212.740856
Male    71.730978  220.042470
Male    69.881796  206.349801

In [61]:
data.describe()

Height        Weight
count  10000.000000  10000.000000
mean      66.367560    161.440357
std        3.847528     32.108439
min       54.263133     64.700127
25%       63.505620    135.818051
50%       66.318070    161.212928
75%       69.174262    187.169525
max       78.998742    269.989699

In [65]:
x = data.Height.values[:, np.newaxis]
y = data.Weight.values

In [66]:
x_train, x_test, y_train, y_test = tts(x, y, test_size = 0.25, random_state = 1)
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [68]:
y_predict = model.predict(x_test)

In [70]:
r2_score(y_test, y_predict)*100

86.63973570518648

# LINEAR REGRESSION W/O PACKAGE

In [98]:
import pandas as pd

data = pd.read_csv("/1683093614543_weight-height.csv")
height = data.Height.values
weight = data.Weight.values

n = len(height)
sum_height_sq = np.sum(height * height)
sum_height_weight = np.sum(height * weight)
sum_height = np.sum(height)
sum_weight = np.sum(weight)

slope = (n * sum_height_weight - sum_height * sum_weight) / (n * sum_height_sq - sum_height ** 2)
intercept = (sum_weight - slope * sum_height) / n

input_height = float(input("Enter a height value: "))
predicted_weight = slope * input_height + intercept
print(predicted_weight)

Enter a height value: 71
197.19023068362628


# DECISION TREE WITH PACKAGE

In [82]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split as tts
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [76]:
data = pd.read_csv('/1683093619109_Iris.csv', index_col = 'Id')
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id                                                                       
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa

In [77]:
data.describe()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count     150.000000    150.000000     150.000000    150.000000
mean        5.843333      3.054000       3.758667      1.198667
std         0.828066      0.433594       1.764420      0.763161
min         4.300000      2.000000       1.000000      0.100000
25%         5.100000      2.800000       1.600000      0.300000
50%         5.800000      3.000000       4.350000      1.300000
75%         6.400000      3.300000       5.100000      1.800000
max         7.900000      4.400000       6.900000      2.500000

In [78]:
features = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']
x = data[features]
y = data['Species']

In [79]:
x_train, x_test, y_train, y_test = tts(x, y, test_size = 0.25, random_state = 1)
model = DecisionTreeClassifier()
model.fit(x_train, y_train)

DecisionTreeClassifier()

In [80]:
y_predict = model.predict(x_test)

In [81]:
accuracy_score(y_test, y_predict)*100

97.36842105263158

In [83]:
confusion_matrix(y_test, y_predict)*100

array([[1300,    0,    0],
       [   0, 1500,  100],
       [   0,    0,  900]])

# LOGISTIC REGRESSION WITH PACKAGE




In [114]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split as tts
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [113]:
x, y = make_classification(n_samples = 100, n_features = 4)
print(x)
print(y)

[[-1.25349716  1.69727025  0.22894418  1.27239682]
 [ 1.14787737 -1.33194364 -0.40113795 -0.85239297]
 [-0.74298056  0.294674    0.74839707 -0.2466604 ]
 [-1.21187776  0.08598397  1.56064221 -0.95760598]
 [-0.66697704 -0.19687032  1.06925449 -0.87060858]
 [-1.25301141  0.85395414  0.95465678  0.08630186]
 [ 2.07332979 -1.54874663 -1.46274347 -0.33376796]
 [ 0.26020509 -0.47176553  0.05535194 -0.43217858]
 [-2.54092671  2.79412536  1.02081133  1.66982251]
 [ 1.09075366  0.26219698 -1.69715426  1.33968728]
 [-0.76021186 -1.21301487  2.07024797 -2.38328164]
 [-0.58285107  1.29621602 -0.33025314  1.30500415]
 [ 1.56099825  0.60496682 -2.62670295  2.24047939]
 [ 0.0992231   0.33568475 -0.42297517  0.56061066]
 [ 0.79105108 -1.10976571 -0.11118191 -0.85737252]
 [-0.2714421  -1.37749153  1.5526139  -2.17968664]
 [ 0.88321669 -0.7815778  -0.51818002 -0.313591  ]
 [-2.32069347  2.42337083  1.04307819  1.34418883]
 [ 1.41518331  0.28688812 -2.15604454  1.66317285]
 [ 0.5209208  -0.29581551 -0.44

In [117]:
x_train, x_test, y_train, y_test = tts(x, y, test_size = 0.25, random_state = 1)
model = LogisticRegression(random_state = 1)
model = MLPClassifier(learning_rate_init = 0.1, random_state = 1)
model.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(learning_rate_init=0.1, random_state=1)

In [118]:
y_predict = model.predict(x_test)

In [119]:
accuracy_score(y_test, y_predict)*100

96.0

# SVM WITH PACKAGE

In [124]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split as tts
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix


In [121]:
x, y = make_classification(n_samples = 100, n_features = 4)
print(x)
print(y)

[[-4.97436175e-01  8.14315369e-01  6.80384672e-01  1.27347301e+00]
 [ 1.03683815e+00 -1.01586355e+00 -1.38724415e+00 -1.48984705e+00]
 [ 6.93179011e-01  5.29194698e-01 -8.72607633e-01  1.06887164e+00]
 [ 1.67086827e+00 -1.06101137e+00 -2.20940702e+00 -1.41649073e+00]
 [-9.27314994e-02 -1.65452240e-01  1.12439312e-01 -3.04748574e-01]
 [-2.04885571e-01  1.49228316e+00  3.32738808e-01  2.50147561e+00]
 [ 8.01302936e-01  4.45503793e-01 -1.01626320e+00  9.51521871e-01]
 [ 7.45949806e-01  5.23679291e-01 -9.41116621e-01  1.07197344e+00]
 [-1.03762818e+00  1.72258102e+00  1.42033726e+00  2.69734496e+00]
 [-4.06397328e-01 -1.17144546e+00  4.72511624e-01 -2.09831506e+00]
 [ 8.76571995e-01  7.11764578e-01 -1.10154021e+00  1.42439346e+00]
 [-2.33915980e+00  9.97942417e-01  3.07097589e+00  1.15007338e+00]
 [ 8.47393917e-01  5.04116300e-01 -1.07322173e+00  1.06262400e+00]
 [ 8.74797308e-01 -7.23962359e-01 -1.16439870e+00 -1.02949275e+00]
 [ 8.76466843e-01  2.39454297e-01 -1.12283788e+00  6.17253520e

In [125]:
x_train, x_test, y_train, y_test = tts(x, y, test_size = 0.25, random_state = 1)
model = SVC(random_state = 1)
model.fit(x_train, y_train)

SVC(random_state=1)

In [126]:
y_predict = model.predict(x_test)

In [127]:
accuracy_score(y_test, y_predict)*100

88.0

In [129]:
confusion_matrix(y_test, y_predict)

array([[11,  1],
       [ 2, 11]])